
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  username: postgres
  password: <%= ENV['POSTGRES_DEV_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_DEV_HOST'] || 'localhost' %>

development:
  <<: *default
  database: pdeif_development
  # password: postgres

test:
  <<: *default
  database: pdeif_test

production:
  <<: *default
  database: pdeif_production
  password: <%= ENV['POSTGRES_PRD_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_PRD_HOST'] || 'localhost' %>
