default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: sgpe_development

test:
  <<: *default
  database: sgpe_test

production:
  <<: *default
  database: <%= ENV['SGPE_DATABASE_NAME'] %>
  host: <%= ENV['SGPE_DATABASE_HOST'] %>
  username: <%= ENV['SGPE_DATABASE_USERNAME'] %>
  password: <%= ENV['SGPE_DATABASE_PASSWORD'] %>
