default: &default
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  sistema_nome:             <%= ENV["SISTEMA_NOME"] %>
  sistema_apelido:          <%= ENV["SISTEMA_APELIDO"] %>
  admin_name:               <%= ENV["ADMIN_NAME"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_username:           <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username:  <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password:  <%= ENV["GMAIL_PASSWORD"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>
  default_url_options:      <%= ENV["DEFAULT_URL_OPTIONS"] %>


development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
