default: &default
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  admin_name:               <%= ENV["ADMIN_NAME"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_username:           <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username:  <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password:  <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  domain_name: example.com
  secret_key_base: 2111ddcdcab8afc5918c634e9f0122cd9b0b976e710d90b9ef24cb560e41f05f634357d43fcf2bc679f87bfbc71b0f52300e160d667c997b43a6c338464bad5c

staging:
  <<: *default

production:
  <<: *default
