default: &default
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  admin_name:               <%= ENV["ADMIN_NAME"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_username:           <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username:  <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password:  <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>
  

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
